describe('test form', ()=>{
    
    beforeEach(()=>{
        cy.visit('http://localhost:3000/pizza')
    })
    const nameInput= () => cy.get('input[name=name]') 
    const sizeInput= () => cy.get('select[name=size]')
    const mushroomInput= () => cy.get('input[name=mushroom]')
    const hamInput= () => cy.get('input[name=ham]')
    const jalapenoInput= () => cy.get('input[name=jalapeno]')
    const oliveInput= () => cy.get('input[name=olive]')
    const extracheeseInput= () => cy.get('input[name=extraCheese]')
    const specialInstruction = () => cy.get('input[name=delivryInstruction')
    const submitBtn = () => cy.get('button')
    const error = () => cy.get('div[class=errorDiv]')



    describe('writing down input and checked', ()=>{
        it('typing name input',()=>{
            nameInput()
            .should('have.value','')
            .type('something')
            .should('not.have.value','')
        })
        it('typing name input',()=>{
            specialInstruction()
            .should('have.value','')
            .type('something')
            .should('not.have.value','')
        })
        it('typing name input',()=>{
            sizeInput()
            .should('have.value','')
            .select('Small: 12 inch , 8 slice')
            .should('not.have.value','')
        })
        it('plenty topping check at same time then un check', ()=>{
            extracheeseInput()
                .should('not.be.checked')
                .check()
                .should('be.checked')
            mushroomInput()
                .should('not.be.checked')
                .check()
                .should('be.checked')
            hamInput()
                .should('not.be.checked')
                .check()
                .should('be.checked')
            jalapenoInput()
                .should('not.be.checked')
                .check()
                .should('be.checked')
            oliveInput()
                .should('not.be.checked')
                .check()
                .should('be.checked') 
            extracheeseInput()
                .should('be.checked')
                .uncheck()
                .should('not.be.checked')
            mushroomInput()
                .should('be.checked')
                .uncheck()
                .should('not.be.checked')
            hamInput()
                .should('be.checked')
                .uncheck()
                .should('not.be.checked')
            jalapenoInput()
                .should('be.checked')
                .uncheck()
                .should('not.be.checked')
            oliveInput()
                .should('be.checked')
                .uncheck()
                .should('not.be.checked')    
        })
        it(' should be able to submit', ()=>{
            submitBtn()
                .should('be.disabled')
            nameInput().type('something')
            sizeInput().select('Small: 12 inch , 8 slice')
            specialInstruction().type('123456789')
            submitBtn()
                .should('not.be.disabled')
                .click()
        })
    })
    

})